"""empty message

Revision ID: 4010c9d5ded9
Revises: None
Create Date: 2016-04-11 09:01:29.416083

"""

# revision identifiers, used by Alembic.
revision = '4010c9d5ded9'
down_revision = None

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('event_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('sensor_serial', sa.String(length=100), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('site_assessment', sa.String(length=100), nullable=True),
    sa.Column('sensor_removal', sa.String(length=50), nullable=True),
    sa.Column('event_type', sa.String(length=50), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('wound_alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('wound_alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('previous_alarm_threshold_hours', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_history_medical_record_number'), 'event_history', ['medical_record_number'], unique=False)
    op.create_table('patient',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_number', sa.String(length=50), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('DOB', sa.String(length=25), nullable=True),
    sa.Column('unit_floor', sa.String(length=50), nullable=True),
    sa.Column('bed_type', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('braden_score', sa.String(length=50), nullable=True),
    sa.Column('mobility', sa.String(length=50), nullable=True),
    sa.Column('diagnosis', sa.String(length=100), nullable=True),
    sa.Column('incontinence', sa.String(length=50), nullable=True),
    sa.Column('medication', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('albumin_level', sa.String(length=50), nullable=True),
    sa.Column('A1C', sa.String(length=50), nullable=True),
    sa.Column('hemoglobin', sa.String(length=50), nullable=True),
    sa.Column('o2_saturation', sa.String(length=50), nullable=True),
    sa.Column('blood_pressure', sa.String(length=50), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_medical_record_number'), 'patient', ['medical_record_number'], unique=True)
    op.create_table('global_device_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('alarm_duration', sa.Integer(), nullable=True),
    sa.Column('alarm_sound', sa.String(length=100), nullable=True),
    sa.Column('alarm_volume', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=150), nullable=True),
    sa.Column('name', sa.Text(), nullable=True),
    sa.Column('password', sa.String(length=100), nullable=True),
    sa.Column('phone_number', sa.String(length=25), nullable=True),
    sa.Column('eula_accepted', sa.Boolean(), nullable=True),
    sa.Column('role', sa.String(length=50), nullable=True),
    sa.Column('previous_sms_sent', sa.DateTime(), nullable=True),
    sa.Column('password_changed', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_email'), 'user', ['email'], unique=True)
    op.create_table('global_location_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('JSID', sa.String(length=100), nullable=True),
    sa.Column('alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('pressure_state', sa.String(length=100), nullable=True),
    sa.Column('wound_stage', sa.String(length=50), nullable=True),
    sa.Column('is_wound', sa.Boolean(), nullable=True),
    sa.Column('has_previous_alert', sa.Boolean(), nullable=True),
    sa.Column('site_assessment', sa.String(length=100), nullable=True),
    sa.Column('sensor_removal', sa.String(length=50), nullable=True),
    sa.Column('wound_measurement', sa.String(length=100), nullable=True),
    sa.Column('existing_wound', sa.Boolean(), nullable=True),
    sa.Column('wound_alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('wound_alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('previous_alarm_threshold_hours', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_global_location_settings_JSID'), 'global_location_settings', ['JSID'], unique=False)
    op.create_table('patient_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('DOB', sa.String(length=25), nullable=True),
    sa.Column('unit_floor', sa.String(length=50), nullable=True),
    sa.Column('bed_type', sa.String(length=50), nullable=True),
    sa.Column('ethnicity', sa.String(length=50), nullable=True),
    sa.Column('braden_score', sa.String(length=50), nullable=True),
    sa.Column('mobility', sa.String(length=50), nullable=True),
    sa.Column('diagnosis', sa.String(length=100), nullable=True),
    sa.Column('incontinence', sa.String(length=50), nullable=True),
    sa.Column('medication', sa.String(length=100), nullable=True),
    sa.Column('weight', sa.Float(), nullable=True),
    sa.Column('height', sa.Float(), nullable=True),
    sa.Column('albumin_level', sa.String(length=50), nullable=True),
    sa.Column('A1C', sa.String(length=50), nullable=True),
    sa.Column('hemoglobin', sa.String(length=50), nullable=True),
    sa.Column('o2_saturation', sa.String(length=50), nullable=True),
    sa.Column('blood_pressure', sa.String(length=50), nullable=True),
    sa.Column('bmi', sa.Float(), nullable=True),
    sa.Column('user', sa.String(length=100), nullable=True),
    sa.Column('date_of_record', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_history_date_of_record'), 'patient_history', ['date_of_record'], unique=False)
    op.create_index(op.f('ix_patient_history_medical_record_number'), 'patient_history', ['medical_record_number'], unique=False)
    op.create_index(op.f('ix_patient_history_user'), 'patient_history', ['user'], unique=False)
    op.create_table('device',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('serial', sa.String(length=100), nullable=True),
    sa.Column('secret', sa.String(length=50), nullable=True),
    sa.Column('name', sa.String(length=100), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('alarm_duration', sa.Integer(), nullable=True),
    sa.Column('alarm_sound', sa.String(length=100), nullable=True),
    sa.Column('alarm_volume', sa.String(length=100), nullable=True),
    sa.Column('language', sa.String(length=50), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('last_device_sync', sa.DateTime(), nullable=True),
    sa.Column('last_web_change', sa.DateTime(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id'),
    sa.UniqueConstraint('secret')
    )
    op.create_index(op.f('ix_device_medical_record_number'), 'device', ['medical_record_number'], unique=True)
    op.create_index(op.f('ix_device_serial'), 'device', ['serial'], unique=True)
    op.create_table('user_patients',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('user_id', 'patient_id')
    )
    op.create_table('body_location',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('sensor_serial', sa.String(length=100), nullable=True),
    sa.Column('stopped', sa.Boolean(), nullable=True),
    sa.Column('fast_blink', sa.Boolean(), nullable=True),
    sa.Column('force_state', sa.Integer(), nullable=True),
    sa.Column('JSID', sa.String(length=100), nullable=True),
    sa.Column('alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('binary_state', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('under_pressure_milliseconds', sa.Integer(), nullable=True),
    sa.Column('pressure_state', sa.String(length=100), nullable=True),
    sa.Column('wound_stage', sa.String(length=50), nullable=True),
    sa.Column('is_wound', sa.Boolean(), nullable=True),
    sa.Column('has_previous_alert', sa.Boolean(), nullable=True),
    sa.Column('site_assessment', sa.String(length=100), nullable=True),
    sa.Column('sensor_removal', sa.String(length=50), nullable=True),
    sa.Column('wound_measurement', sa.String(length=100), nullable=True),
    sa.Column('wound_existing_since', sa.DateTime(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('existing_wound', sa.Boolean(), nullable=True),
    sa.Column('wound_alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('wound_alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('previous_alarm_threshold_hours', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_location_JSID'), 'body_location', ['JSID'], unique=False)
    op.create_index(op.f('ix_body_location_medical_record_number'), 'body_location', ['medical_record_number'], unique=False)
    op.create_table('event',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('body_location_id', sa.Integer(), nullable=True),
    sa.Column('message', sa.String(length=100), nullable=True),
    sa.Column('instance', sa.DateTime(), nullable=True),
    sa.Column('range_start', sa.DateTime(), nullable=True),
    sa.Column('range_end', sa.DateTime(), nullable=True),
    sa.Column('location', sa.String(length=100), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['body_location_id'], ['body_location.id'], ),
    sa.ForeignKeyConstraint(['device_id'], ['device.id'], ),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_event_medical_record_number'), 'event', ['medical_record_number'], unique=False)
    op.create_index(op.f('ix_event_message'), 'event', ['message'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_message'), table_name='event')
    op.drop_index(op.f('ix_event_medical_record_number'), table_name='event')
    op.drop_table('event')
    op.drop_index(op.f('ix_body_location_medical_record_number'), table_name='body_location')
    op.drop_index(op.f('ix_body_location_JSID'), table_name='body_location')
    op.drop_table('body_location')
    op.drop_table('user_patients')
    op.drop_index(op.f('ix_device_serial'), table_name='device')
    op.drop_index(op.f('ix_device_medical_record_number'), table_name='device')
    op.drop_table('device')
    op.drop_index(op.f('ix_patient_history_user'), table_name='patient_history')
    op.drop_index(op.f('ix_patient_history_medical_record_number'), table_name='patient_history')
    op.drop_index(op.f('ix_patient_history_date_of_record'), table_name='patient_history')
    op.drop_table('patient_history')
    op.drop_index(op.f('ix_global_location_settings_JSID'), table_name='global_location_settings')
    op.drop_table('global_location_settings')
    op.drop_index(op.f('ix_user_email'), table_name='user')
    op.drop_table('user')
    op.drop_table('global_device_settings')
    op.drop_index(op.f('ix_patient_medical_record_number'), table_name='patient')
    op.drop_table('patient')
    op.drop_index(op.f('ix_event_history_medical_record_number'), table_name='event_history')
    op.drop_table('event_history')
    ### end Alembic commands ###
