"""empty message

Revision ID: 74f9d453f026
Revises: 4010c9d5ded9
Create Date: 2016-04-14 15:40:02.303900

"""

# revision identifiers, used by Alembic.
revision = '74f9d453f026'
down_revision = '4010c9d5ded9'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_patients')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_patients',
    sa.Column('user_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.Column('patient_id', mysql.INTEGER(display_width=11), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['patient_id'], [u'patient.id'], name=u'user_patients_ibfk_1'),
    sa.ForeignKeyConstraint(['user_id'], [u'user.id'], name=u'user_patients_ibfk_2'),
    sa.PrimaryKeyConstraint('user_id', 'patient_id'),
    mysql_default_charset=u'utf8',
    mysql_engine=u'InnoDB'
    )
    ### end Alembic commands ###
