"""empty message

Revision ID: e4b46379841e
Revises: d733999c96ff
Create Date: 2016-05-17 07:49:07.844320

"""

# revision identifiers, used by Alembic.
revision = 'e4b46379841e'
down_revision = 'd733999c96ff'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('diagnosis',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('diabetes', sa.Boolean(), nullable=True),
    sa.Column('heart_disease', sa.Boolean(), nullable=True),
    sa.Column('stroke', sa.Boolean(), nullable=True),
    sa.Column('immobility', sa.Boolean(), nullable=True),
    sa.Column('pvd', sa.Boolean(), nullable=True),
    sa.Column('neuropathy', sa.Boolean(), nullable=True),
    sa.Column('incontinence', sa.Boolean(), nullable=True),
    sa.Column('malnutrition', sa.Boolean(), nullable=True),
    sa.Column('heart_attack', sa.Boolean(), nullable=True),
    sa.Column('prior_skin_pressure_injury', sa.Boolean(), nullable=True),
    sa.Column('hip_pelvic_fracture', sa.Boolean(), nullable=True),
    sa.Column('femur_fracture', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('medication',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('none', sa.Boolean(), nullable=True),
    sa.Column('steroids', sa.Boolean(), nullable=True),
    sa.Column('vasopressors', sa.Boolean(), nullable=True),
    sa.Column('heart_rhythm', sa.Boolean(), nullable=True),
    sa.Column('blood_pressure', sa.Boolean(), nullable=True),
    sa.Column('narcotic_pain', sa.Boolean(), nullable=True),
    sa.Column('non_narcotic_pain', sa.Boolean(), nullable=True),
    sa.Column('hypoglycemic', sa.Boolean(), nullable=True),
    sa.Column('sleeping', sa.Boolean(), nullable=True),
    sa.Column('constipation_relief', sa.Boolean(), nullable=True),
    sa.Column('anxiety_control', sa.Boolean(), nullable=True),
    sa.Column('antispasmodics', sa.Boolean(), nullable=True),
    sa.Column('antibiotics', sa.Boolean(), nullable=True),
    sa.Column('other', sa.Boolean(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('patient_id')
    )
    op.create_table('patient_activation',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(length=50), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['patient_id'], ['patient.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('patient', sa.Column('date_of_admission', sa.Date(), nullable=True))
    op.add_column('patient', sa.Column('units', sa.String(length=50), nullable=True))
    op.add_column('patient_history', sa.Column('date_of_admission', sa.Date(), nullable=True))
    op.add_column('patient_history', sa.Column('units', sa.String(length=50), nullable=True))
    op.drop_column('patient', 'medication')
    op.drop_column('patient', 'diagnosis')
    op.alter_column('body_location', 'site_assessment', type_=sa.Text())
    op.alter_column('body_location', 'sensor_removal', type_=sa.Text())
    op.alter_column('patient_history', 'medication', type_=sa.Text())
    op.alter_column('patient_history', 'diagnosis', type_=sa.Text())
    op.alter_column('patient', 'DOB', type_=sa.Date())
    op.alter_column('patient_history', 'DOB', type_=sa.Date())
    op.add_column('body_location', sa.Column('outcome', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient', sa.Column('diagnosis', mysql.DATETIME(), nullable=True))
    op.add_column('patient', sa.Column('medication', mysql.TEXT(), nullable=True))
    op.drop_column('patient', 'units')
    op.drop_column('patient', 'date_of_admission')
    op.drop_column('patient_history', 'date_of_admission')
    op.drop_column('patient_history', 'units')
    op.drop_column('body_location', 'outcome')
    op.drop_table('patient_activation')
    op.drop_table('medication')
    op.drop_table('diagnosis')
    ### end Alembic commands ###
