"""empty message

Revision ID: 33e19a2e5c31
Revises: e9c747b27da4
Create Date: 2016-06-14 13:32:36.180339

"""

# revision identifiers, used by Alembic.
revision = '33e19a2e5c31'
down_revision = 'e9c747b27da4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('body_location_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=100), nullable=True),
    sa.Column('sensor_serial', sa.String(length=200), nullable=True),
    sa.Column('stopped', sa.Boolean(), nullable=True),
    sa.Column('fast_blink', sa.Boolean(), nullable=True),
    sa.Column('force_state', sa.Integer(), nullable=True),
    sa.Column('JSID', sa.String(length=100), nullable=True),
    sa.Column('alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('battery', sa.Integer(), nullable=True),
    sa.Column('binary_state', sa.Boolean(), nullable=True),
    sa.Column('last_seen', sa.DateTime(), nullable=True),
    sa.Column('distance', sa.Float(), nullable=True),
    sa.Column('under_pressure_milliseconds', sa.Integer(), nullable=True),
    sa.Column('pressure_state', sa.String(length=100), nullable=True),
    sa.Column('wound_stage', sa.String(length=50), nullable=True),
    sa.Column('is_wound', sa.Boolean(), nullable=True),
    sa.Column('has_previous_alert', sa.Boolean(), nullable=True),
    sa.Column('site_assessment', sa.Text(), nullable=True),
    sa.Column('sensor_removal', sa.Text(), nullable=True),
    sa.Column('wound_measurement', sa.String(length=200), nullable=True),
    sa.Column('wound_existing_since', sa.DateTime(), nullable=True),
    sa.Column('medical_record_number', sa.String(length=100), nullable=True),
    sa.Column('existing_wound', sa.Boolean(), nullable=True),
    sa.Column('wound_alarm_threshold_minutes', sa.Integer(), nullable=True),
    sa.Column('wound_alarm_clear_multiple', sa.Integer(), nullable=True),
    sa.Column('previous_alarm_threshold_hours', sa.Integer(), nullable=True),
    sa.Column('deleted', sa.Boolean(), nullable=True),
    sa.Column('wound_outcome', sa.Text(), nullable=True),
    sa.Column('body_location_id', sa.Integer(), nullable=True),
    sa.Column('date_of_record', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_body_location_history_date_of_record'), 'body_location_history', ['date_of_record'], unique=False)
    op.create_index(op.f('ix_body_location_history_JSID'), 'body_location_history', ['JSID'], unique=False)
    op.create_index(op.f('ix_body_location_history_body_location_id'), 'body_location_history', ['body_location_id'], unique=False)
    op.create_index(op.f('ix_body_location_history_medical_record_number'), 'body_location_history', ['medical_record_number'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_body_location_history_date_of_record'), table_name='body_location_history')
    op.drop_index(op.f('ix_body_location_history_medical_record_number'), table_name='body_location_history')
    op.drop_index(op.f('ix_body_location_history_body_location_id'), table_name='body_location_history')
    op.drop_index(op.f('ix_body_location_history_JSID'), table_name='body_location_history')
    op.drop_table('body_location_history')
    ### end Alembic commands ###
