"""empty message

Revision ID: 78c75b49f005
Revises: 33e19a2e5c31
Create Date: 2016-08-01 08:36:02.203049

"""

# revision identifiers, used by Alembic.
revision = '78c75b49f005'
down_revision = '33e19a2e5c31'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('admin_default',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('unit_floor', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column(u'event', sa.Column('unit_floor', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_event_unit_floor'), 'event', ['unit_floor'], unique=False)
    op.add_column(u'event_history', sa.Column('unit_floor', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_event_history_unit_floor'), 'event_history', ['unit_floor'], unique=False)
    op.add_column(u'patient', sa.Column('room', sa.Text(), nullable=True))
    op.add_column(u'patient_history', sa.Column('room', sa.String(length=100), nullable=True))
    op.add_column(u'event', sa.Column('latest', sa.String(length=100), nullable=True))
    op.create_index(op.f('ix_event_latest'), 'event', ['latest'], unique=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_latest'), table_name='event')
    op.drop_column(u'event', 'latest')
    op.drop_column(u'patient_history', 'room')
    op.drop_column(u'patient', 'room')
    op.drop_index(op.f('ix_event_history_unit_floor'), table_name='event_history')
    op.drop_column(u'event_history', 'unit_floor')
    op.drop_index(op.f('ix_event_unit_floor'), table_name='event')
    op.drop_column(u'event', 'unit_floor')
    op.drop_table('admin_default')
    ### end Alembic commands ###
