"""empty message

Revision ID: 880816bd6e7c
Revises: 78c75b49f005
Create Date: 2016-08-04 17:51:29.017186

"""

# revision identifiers, used by Alembic.
revision = '880816bd6e7c'
down_revision = '78c75b49f005'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('patient_note',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('pa_id', sa.String(length=100), nullable=True),
    sa.Column('patient_site', sa.String(length=100), nullable=True),
    sa.Column('patient_site_other', sa.Text(), nullable=True),
    sa.Column('dressing_application_surface', sa.String(length=100), nullable=True),
    sa.Column('dressing_application_surface_other', sa.Text(), nullable=True),
    sa.Column('device_surrounding_dressing', sa.String(length=100), nullable=True),
    sa.Column('device_surrounding_dressing_other', sa.Text(), nullable=True),
    sa.Column('reason_for_dressing_change', sa.String(length=100), nullable=True),
    sa.Column('reason_for_dressing_change_other', sa.Text(), nullable=True),
    sa.Column('reason_for_dressing_removal', sa.String(length=100), nullable=True),
    sa.Column('reason_for_dressing_removal_other', sa.Text(), nullable=True),
    sa.Column('tablet_issues', sa.String(length=100), nullable=True),
    sa.Column('tablet_issues_other', sa.Text(), nullable=True),
    sa.Column('sensor_issues', sa.String(length=100), nullable=True),
    sa.Column('sensor_issues_other', sa.Text(), nullable=True),
    sa.Column('support_contacted', sa.Boolean(), nullable=True),
    sa.Column('support_reason', sa.Text(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.Column('user', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_patient_note_occurred'), 'patient_note', ['occurred'], unique=False)
    op.create_index(op.f('ix_patient_note_pa_id'), 'patient_note', ['pa_id'], unique=False)
    op.create_index(op.f('ix_patient_note_patient_site'), 'patient_note', ['patient_site'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_patient_note_patient_site'), table_name='patient_note')
    op.drop_index(op.f('ix_patient_note_pa_id'), table_name='patient_note')
    op.drop_index(op.f('ix_patient_note_occurred'), table_name='patient_note')
    op.drop_table('patient_note')
    ### end Alembic commands ###
