"""empty message

Revision ID: 3708cdab96ad
Revises: 880816bd6e7c
Create Date: 2016-08-24 19:10:37.101450

"""

# revision identifiers, used by Alembic.
revision = '3708cdab96ad'
down_revision = '880816bd6e7c'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_body_location_sensor_serial'), 'body_location', ['sensor_serial'], unique=False)
    op.create_index(op.f('ix_device_last_seen'), 'device', ['last_seen'], unique=False)
    op.create_index(op.f('ix_event_instance'), 'event', ['instance'], unique=False)
    op.create_index(op.f('ix_event_location'), 'event', ['location'], unique=False)
    op.create_index(op.f('ix_event_range_end'), 'event', ['range_end'], unique=False)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_event_range_end'), table_name='event')
    op.drop_index(op.f('ix_event_location'), table_name='event')
    op.drop_index(op.f('ix_event_instance'), table_name='event')
    op.drop_index(op.f('ix_device_last_seen'), table_name='device')
    op.drop_index(op.f('ix_body_location_sensor_serial'), table_name='body_location')
    ### end Alembic commands ###
