"""empty message

Revision ID: ad230d7ad3b5
Revises: 3708cdab96ad
Create Date: 2016-09-20 11:08:48.498567

"""

# revision identifiers, used by Alembic.
revision = 'ad230d7ad3b5'
down_revision = '3708cdab96ad'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_activation', sa.Column('reason_other', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('patient_activation', 'reason_other')
    ### end Alembic commands ###
