"""empty message

Revision ID: b7df41979e23
Revises: ad230d7ad3b5
Create Date: 2016-09-25 16:06:04.251658

"""

# revision identifiers, used by Alembic.
revision = 'b7df41979e23'
down_revision = 'ad230d7ad3b5'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_response',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('hour', sa.Integer(), nullable=True),
    sa.Column('pa_id', sa.String(length=100), nullable=True),
    sa.Column('alarms_occurred', sa.Integer(), nullable=True),
    sa.Column('patient_repositions', sa.Integer(), nullable=True),
    sa.Column('caregiver_repositions', sa.Integer(), nullable=True),
    sa.Column('total_repositions', sa.Integer(), nullable=True),
    sa.Column('minutes_alarming', sa.String(length=60), nullable=True),
    sa.Column('unit_floor', sa.String(length=100), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_response_date'), 'alarm_response', ['date'], unique=False)
    op.create_index(op.f('ix_alarm_response_hour'), 'alarm_response', ['hour'], unique=False)
    op.create_index(op.f('ix_alarm_response_pa_id'), 'alarm_response', ['pa_id'], unique=False)
    op.create_index(op.f('ix_alarm_response_unit_floor'), 'alarm_response', ['unit_floor'], unique=False)

    op.add_column('admin_default', sa.Column('alert_reponse_window', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('admin_default', 'alert_reponse_window')
    op.drop_index(op.f('ix_alarm_response_unit_floor'), table_name='alarm_response')
    op.drop_index(op.f('ix_alarm_response_pa_id'), table_name='alarm_response')
    op.drop_index(op.f('ix_alarm_response_hour'), table_name='alarm_response')
    op.drop_index(op.f('ix_alarm_response_date'), table_name='alarm_response')
    op.drop_table('alarm_response')
    ### end Alembic commands ###
