"""empty message

Revision ID: 58f62c2f0614
Revises: 15b0fe720940
Create Date: 2016-10-24 13:26:41.237633

"""

# revision identifiers, used by Alembic.
revision = '58f62c2f0614'
down_revision = '15b0fe720940'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('large_request',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_id', sa.Integer(), nullable=True),
    sa.Column('patient_id', sa.Integer(), nullable=True),
    sa.Column('request', sa.Text(), nullable=True),
    sa.Column('request_class', sa.String(length=100), nullable=True),
    sa.Column('request_action', sa.String(length=100), nullable=True),
    sa.Column('occurred', sa.DateTime(), nullable=True),
    sa.Column('processing', sa.Boolean(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('large_request')
    ### end Alembic commands ###
