"""empty message

Revision ID: 6a22c5904e65
Revises: 966e100f2c89
Create Date: 2016-11-07 08:51:35.131066

"""

# revision identifiers, used by Alembic.
revision = '6a22c5904e65'
down_revision = '966e100f2c89'

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alarm_response_report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pa_id', sa.String(length=100), nullable=True),
    sa.Column('unit_floor', sa.String(length=100), nullable=True),
    sa.Column('all', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_alarm_response_report_data_date'), 'alarm_response_report_data', ['date'], unique=False)
    op.create_index(op.f('ix_alarm_response_report_data_pa_id'), 'alarm_response_report_data', ['pa_id'], unique=False)
    op.create_index(op.f('ix_alarm_response_report_data_unit_floor'), 'alarm_response_report_data', ['unit_floor'], unique=False)
    op.create_table('reposition_report_data',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('date', sa.Date(), nullable=True),
    sa.Column('pa_id', sa.String(length=100), nullable=True),
    sa.Column('unit_floor', sa.String(length=100), nullable=True),
    sa.Column('all', sa.Boolean(), nullable=True),
    sa.Column('data', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_reposition_report_data_date'), 'reposition_report_data', ['date'], unique=False)
    op.create_index(op.f('ix_reposition_report_data_pa_id'), 'reposition_report_data', ['pa_id'], unique=False)
    op.create_index(op.f('ix_reposition_report_data_unit_floor'), 'reposition_report_data', ['unit_floor'], unique=False)
    op.alter_column(u'large_request', 'request',
               existing_type=mysql.LONGTEXT(),
               nullable=True)
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.alter_column(u'large_request', 'request',
               existing_type=mysql.LONGTEXT(),
               nullable=False)
    op.drop_index(op.f('ix_reposition_report_data_unit_floor'), table_name='reposition_report_data')
    op.drop_index(op.f('ix_reposition_report_data_pa_id'), table_name='reposition_report_data')
    op.drop_index(op.f('ix_reposition_report_data_date'), table_name='reposition_report_data')
    op.drop_table('reposition_report_data')
    op.drop_index(op.f('ix_alarm_response_report_data_unit_floor'), table_name='alarm_response_report_data')
    op.drop_index(op.f('ix_alarm_response_report_data_pa_id'), table_name='alarm_response_report_data')
    op.drop_index(op.f('ix_alarm_response_report_data_date'), table_name='alarm_response_report_data')
    op.drop_table('alarm_response_report_data')
    ### end Alembic commands ###
