"""empty message

Revision ID: f8f4148a6bb6
Revises: 6a22c5904e65
Create Date: 2016-11-28 13:55:33.363860

"""

# revision identifiers, used by Alembic.
revision = 'f8f4148a6bb6'
down_revision = '6a22c5904e65'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_notification', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_notification')
    ### end Alembic commands ###
