"""empty message

Revision ID: c554c9708478
Revises: f8f4148a6bb6
Create Date: 2016-12-05 22:05:46.677829

"""

# revision identifiers, used by Alembic.
revision = 'c554c9708478'
down_revision = 'f8f4148a6bb6'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('diagnosis', sa.Column('respiratory_failure', sa.Boolean(), nullable=True))
    op.add_column('diagnosis', sa.Column('skin_flap_graft', sa.Boolean(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('diagnosis', 'skin_flap_graft')
    op.drop_column('diagnosis', 'respiratory_failure')
    ### end Alembic commands ###
