"""empty message

Revision ID: a698a406ace6
Revises: c554c9708478
Create Date: 2016-12-09 09:47:14.344884

"""

# revision identifiers, used by Alembic.
revision = 'a698a406ace6'
down_revision = 'c554c9708478'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column('body_location', sa.Column('wound_acquisition', sa.Text(), nullable=True))
    op.add_column('body_location_history', sa.Column('wound_acquisition', sa.Text(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('body_location', 'wound_acquisition')
    op.drop_column('body_location_history', 'wound_acquisition')
    ### end Alembic commands ###
