DIAGNOSIS_FIELD_NAMES = []
DIAGNOSIS_FIELD_NAMES.append({'name': 'diabetes', 'display_name': 'Diabetes'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'heart_disease', 'display_name': 'Heart Disease'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'stroke', 'display_name': 'Stroke'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'immobility', 'display_name': 'Immobility (stroke, paraplegic, quadriplegic)'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'pvd', 'display_name': 'PVD (peripheral vascular disease)'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'neuropathy', 'display_name': 'Neuropathy'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'incontinence', 'display_name': 'Incontinence'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'malnutrition', 'display_name': 'Malnutrition'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'heart_attack', 'display_name': 'CAD'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'prior_skin_pressure_injury', 'display_name': 'Prior skin pressure injury'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'skin_flap_graft', 'display_name': 'Skin Flap / Graft'}) 
DIAGNOSIS_FIELD_NAMES.append({'name': 'hip_pelvic_fracture', 'display_name': 'Hip/femur fracture'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'femur_fracture', 'display_name': 'Pelvic fracture'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'hypertension', 'display_name': 'Hypertension'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'respiratory_failure', 'display_name': 'Respiratory Failure'}) 
DIAGNOSIS_FIELD_NAMES.append({'name': 'malignancy', 'display_name': 'Malignancy'})
DIAGNOSIS_FIELD_NAMES.append({'name': 'other', 'display_name': 'Other'})

MEDICATION_FIELD_NAMES = []
MEDICATION_FIELD_NAMES.append({'name': 'none', 'display_name': 'None'})
MEDICATION_FIELD_NAMES.append({'name': 'steroids', 'display_name': 'Steroids'})
MEDICATION_FIELD_NAMES.append({'name': 'vasopressors', 'display_name': 'Vasopressors'})
MEDICATION_FIELD_NAMES.append({'name': 'heart_rhythm', 'display_name': 'Heart rhythm'})
MEDICATION_FIELD_NAMES.append({'name': 'blood_pressure', 'display_name': 'Blood pressure'})
MEDICATION_FIELD_NAMES.append({'name': 'narcotic_pain', 'display_name': 'Narcotic pain control'})
MEDICATION_FIELD_NAMES.append({'name': 'non_narcotic_pain', 'display_name': 'Non-narcotic pain'})
MEDICATION_FIELD_NAMES.append({'name': 'hypoglycemic', 'display_name': 'Hypoglycemic'})
MEDICATION_FIELD_NAMES.append({'name': 'sleeping', 'display_name': 'Sleeping'})
MEDICATION_FIELD_NAMES.append({'name': 'constipation_relief', 'display_name': 'Constipation relief'})
MEDICATION_FIELD_NAMES.append({'name': 'anxiety_control', 'display_name': 'Psychoactive Medications'})
MEDICATION_FIELD_NAMES.append({'name': 'antispasmodics', 'display_name': 'Antispasmodics'})
MEDICATION_FIELD_NAMES.append({'name': 'antibiotics', 'display_name': 'Antibiotics'})
MEDICATION_FIELD_NAMES.append({'name': 'chemotherapy', 'display_name': 'Chemotherapy'})
MEDICATION_FIELD_NAMES.append({'name': 'radiation', 'display_name': 'Radiation'})
MEDICATION_FIELD_NAMES.append({'name': 'other', 'display_name': 'Other'})